name: Manual pushing to GitLab

on: workflow_dispatch

jobs:
  push_to_gitlab:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: arthurkazaryants/action-sync-repos@v1
      with:
        target_repo_url:
          git@gitlab.com:arthurkazaryants/deployment.git
        ssh_private_key:
          ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        source_branch:
          master
